server:
  port: ${PORT:8098}
  forward-headers-strategy: framework

spring:
  application:
    name: ${INFORME_NAME}
eureka:
  preferIpAddress: true
  hostname: ${HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: ${TEMPO_HTTP_INGEST:http://tempo.railway.internal:4318/api/v2/spans}
  endpoint:
    health:
      show:
        details: "always"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true