server:
  port: ${PORT:8090}

spring:
  application:
    name: ${INVENTORY_NAME}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  preferIpAddress: true
  hostname: ${HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,trace
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      base-url: ${TEMPO_HTTP_INGEST}
      enabled: true
